version: '3.8'

services:
  prolog-server:
    build: .
    ports:
      - "8080:8080" 
    volumes:
      - .:/app  
    environment:
      - SWI_PROLOG_HOME=/usr/local/lib/swi-prolog 
    networks:
      - plant_care_network

networks:
  plant_care_network:
    driver: bridge
